name: Rollback DNS Configuration

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest stable version

    - name: Revert last commit
      run: |
        git revert --no-commit HEAD~1
        git commit -m "Revert last DNS change"
        git push

    - name: Install dnscontrol
      run: |
        curl -L -o dnscontrol https://github.com/StackExchange/dnscontrol/releases/latest/download/dnscontrol-Linux
        chmod +x dnscontrol

    - name: Push reverted DNS changes
      run: ./dnscontrol push


# optional: send notification via Apprise
#   - name: Send Notification using Apprise
#       if: always() # ensure this step runs even if the rollback fails
#         run: |
#           docker run -v ${{ github.workspace }}:/config caronc/apprise -vv -c /config/apprise.yml -b "Rollback action executed. Status: ${{ job.status }}"
