name: Update DNS Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'dnsconfig.js'
  workflow_dispatch:

jobs:
  preview:
    name: Preview DNS Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dnscontrol
        id: cache-dnscontrol
        uses: actions/cache@v3
        with:
          path: dnscontrol
          key: ${{ runner.os }}-dnscontrol

      - name: Install dnscontrol
        if: steps.cache-dnscontrol.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/StackExchange/dnscontrol/releases/latest/download/dnscontrol-Linux -O dnscontrol
          chmod +x dnscontrol

      - name: Preview DNS changes
        run: ./dnscontrol preview

  push:
    name: Push DNS Changes
    runs-on: ubuntu-latest
    needs: preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dnscontrol
        id: cache-dnscontrol
        uses: actions/cache@v3
        with:
          path: dnscontrol
          key: ${{ runner.os }}-dnscontrol

      - name: Install dnscontrol
        if: steps.cache-dnscontrol.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/StackExchange/dnscontrol/releases/latest/download/dnscontrol-Linux -O dnscontrol
          chmod +x dnscontrol

      - name: Push DNS changes
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        run: ./dnscontrol push
